### PR TITLE
Rename Message Pack to MessagePack

### PR DESCRIPTION
**Pull request by moka491**
To prevent any unwanted confusion, I carefully implemented the necessary changes to solve this problem of utmost importance.

### CODE REVIEW

**Comment by Trivernis** [comment]
Next time please create an issue before opening a PR 🙂

**Comment by moka491** [comment]
> Next time please create an issue before opening a PR 🙂

Blame Mittens for not opening an issue :P

**Comment by Trivernis** [comment]
> > Next time please create an issue before opening a PR slightly_smiling_face
> 
> Blame Mittens for not opening an issue :P

You started the PR

**Comment by moka491** [comment]
I will keep it in mind next time, thank you for your feedback ;)

**Pull request merged**
